---
- name: Install Solarized Proxmox theme
# Playbook: solarized-theme.yml
# Author: Dieter Beckers & vhsdream
# Github: https://github.com/dabeastnet/SolarPVE
# Description: Install Solarized Proxmox theme (automatic light + dark-mode detection)
# License: CC BY-NC 4.0.
#
# Change this to match your inventory grouping
  hosts: pve
  become: true
  vars:
    css_src: files/solarized.css
    css_dest: /usr/share/pve-manager/images/solarized.css
    tpl_path: /usr/share/pve-manager/index.html.tpl
  tasks:

    - name: Ensure Proxmox images directory exists
      file:
        path: "{{ css_dest | dirname }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy Solarized CSS into place
      copy:
        src: "{{ css_src }}"
        dest: "{{ css_dest }}"
        owner: root
        group: root
        mode: '0644'

    - name: Inject auto-theme-mode detector + Solarized link into index.html.tpl
      blockinfile:
        path: "{{ tpl_path }}"
        backup: yes
        marker: "<!-- {mark} solarized theme -->"
        insertbefore: "</body>"
        block: |
          <script>
            function setSolarizedThemeMode() {
              const defaultMode = window.matchMedia('(prefers-color-scheme: dark)').matches;
              const selectedTheme = document.cookie.split("; ")
              .find((row) => row.startsWith("PVEThemeCookie="))
              ?.split("=")[1];

              if (defaultMode && selectedTheme !== "crisp") {
                document.body.classList.add('proxmox-theme-dark');
              } else if (selectedTheme !== "proxmox-dark") {
                document.body.classList.remove('proxmox-theme-dark');
              } else {
                document.body.classList.add('proxmox-theme-dark');
              }
            }

            window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', setSolarizedThemeMode);
            setSolarizedThemeMode();
          </script>
          <link rel="stylesheet" href="/pve2/images/solarized.css">

    - name: Restart pveproxy so new CSS is served
      service:
        name: pveproxy
        state: restarted
